baseurl = "https://soerenetler.de/"
metaDataFormat = "yaml"
title = "Sören Etler - Datenanlysen und Künstliche Intelligenz"
theme = "blist"
timeout = "120s"

DefaultContentLanguage = "de"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.de]
    contentDir = "content/de" # Deutsch
    weight = 2
    languageName = "Deutsch"
    [languages.de.params]
      description = "Ich bin der Open Data Analyst."
      introTitle = "Moin, ich bin Sören Etler"
      introSubtitle = "Ich bin Datenanalyst und habe mich auf die Arbeit mit Sprach- und Geodaten spezialisiert. Als Open Data Analyst unterstütze ich Organisationen dabei, aus ihren Daten Erkenntnisse zu gewinnen und diese zu kommunizieren. Dazu gehören Analysen, Visualisierungen und Vorträge rund um die Themen Daten und KI."
      introPhoto = "/picture.png"
      logo = "/blist-logo.png"

    [[languages.de.menu.main]]
        name = "Über mich"
        url = "page/about/"
        weight = 2
        

[params]
  logo = "/blist-logo.png"

  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2024 - Sören Etler · All rights reserved · <a href=/de/page/impressum>Impressum</a>"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = false

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "👋 Schreib mir"
  description = "Ob ein interessanter Datensatz, beeindruckenden Visualisierungen oder ein Impulsvortrag zu KI. Du hast Interesse mit mir zusammenzuarbeiten? Schreib mir eine Nachricht!"

  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://www.linkedin.com/in/soeren-etler/"
  [[params.homepage.social.icons]]
    website = "email"
    url = "moin@soerenetler.de"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
